### ISSUE TITLE
0.15 // Additional debugging tools

### ISSUE THREAD

**Issue by geowurster** [GlobalFishingWatch/pelagos-client#126]
Two debugging feature requests:

**Show Zoom Level**

It would be very useful if the debug tools could tell us the zoom level we are seeing in the visualization, and even more useful if it would show us as we mouse around from tile to tile since tiles fail up and we may not be seeing what we think we are seeing.

@redhog mentioned that this is possible with something like the snippet below but I couldn't get it to work:

``` javascript
a = visualization.animations.animations[4];
require(['app/Data/TileBounds'], function (TileBounds) {
 console.log(TileBounds.tileParamsForRegion(a.data_view.source.bounds, a.data_view.source.tilesPerScreen).level);
});
```

**Tile Bounds**

Also useful would be a view that displayed tile bounds on the map with an option to highlight the geometries as they are moused over.

It was initially difficult to determine if the issues covered in https://github.com/SkyTruth/benthos-pipeline/issues/362 are due to missing tiles or something else.  Both of the feature requests above would have made debugging easier.

**Visualizing 404's**

Being able to visualize which tiles are causing a 404 would also be very useful.  We could do this by having an option to prevent the client from failing up, or maybe highlighting the tile bounds in a semi-transparent box so we can determine if the tile is just in an area with low traffic.

**Comment by redhog** [comment]
+1 on these - these are good things to add, and not terribly hard to build

**Comment by enriquetuya** [comment]
Let's work on them on the 15 SPRINT.

**Comment by redhog** [comment]
How to use the debugging tools:
- To find out tile data for a vessel point
  - Shift-click the vessel point. Point data, including tile name, level, tags, loading status etc is displayed in the info pane
- To find out about all loaded tiles and their levels
  - Switch to the edit sidebar, select the Data pane. Tiles are displayed with their name, level, tags, loading status etc.
- To get a visual overview of what tiles are loaded, loading or have errors
  - Switch to the editing sidebar.
  - Select the Layers pane
  - Click the + symbol at the top
  - In the first animation, select "TileAnimation"
  - In the second drop down (this one is very narrow, and has no value by default), select the data source of the main animation, e.g. TiledBinFormat: http://localhost:8080/tile/pipeline_2015_08_07_13_33_31)
  - Click add

In the visual overview mode you can click the wire frames to get tile information
Color guide: red: 404, green: loaded, blue: loading, white: selected

**Comment by redhog** [comment]
I assigned it to you. If you are uncomfortable evaluating and merging send it on to Andres

**Comment by geowurster** [comment]
@redhog How and where am I to evaluate this?

**Comment by redhog** [comment]
You can just run it on local host (possibly using the Vagrant setup).

```
make dev-server
```

Then go to localhost:8000/index.html?workspace=URLENCODED_WORKSPACE_URL

**Comment by geowurster** [comment]
Ah right.  Thanks!

**Comment by enriquetuya** [comment]
Please resolve on the `release-0.15` branch.

Tested on 0.15.0 with http://alpha-dev.globalfishingwatch.org/viz?workspace=/workspace/9e203432-a1c5-44a0-a7a4-2f7508f7a44e
- [ ] When shift clicking on a vessel I got the error:
  `Uncaught TypeError: Cannot read property '0' of undefined` on the console. Following this one here: https://github.com/SkyTruth/pelagos-server/issues/1041
- [ ] I also could not get the `To get a visual overview of what tiles are loaded, loading or have errors` working. I follow your steps detailed on https://github.com/SkyTruth/pelagos-client/issues/126#issuecomment-194302634 but did not get any visual overview. If you were able to have it working please do an screencast.

**Comment by redhog** [comment]
@enriquetuya  Please clarify the last note, how did the latter it not work?

**Comment by enriquetuya** [comment]
@redhog updated comment above.

**Comment by redhog** [comment]
But you still didn't explain what you meant by "I also could not get the To get a visual overview of what tiles are loaded, loading or have errors working.".... What did you click, what did you expect to see, and what did you see instead?

**Comment by enriquetuya** [comment]
@redhog check the comment I mentioned: https://github.com/SkyTruth/pelagos-client/issues/126#issuecomment-194302634

I follow the steps you mentioned:

```
To get a visual overview of what tiles are loaded, loading or have errors

Switch to the editing sidebar.
Select the Layers pane
Click the + symbol at the top
In the first animation, select "TileAnimation"
In the second drop down (this one is very narrow, and has no value by default), select the data source of the main animation, e.g. TiledBinFormat: http://localhost:8080/tile/pipeline_2015_08_07_13_33_31)
Click add
```

And did not get anything displaying which tiles are loaded and which ones are not.

**Comment by redhog** [comment]
Ah so you add the tile animation, but it doesn't change the map? Does it show up in the layer list?

**Comment by enriquetuya** [comment]
@redhog It does show on the list but does not change the map. Please go ahead and try it yourself. If it works for you create a screncast of how to do it.

**Comment by redhog** [comment]
This is working on release-0.15 when run on /workspace%3Fid%3Dpipeline_2015_08_07_13_33_31 but not on /workspace/9e203432-a1c5-44a0-a7a4-2f7508f7a44e Strange.

**Comment by enriquetuya** [comment]
@redhog tests are failing with 

```
        Log: |
            { type: 'error',
              text: 'TypeError: startTile.printTree is not a function at http://localhost:8080/5003/js/app/Data/Selection.js, line 52\n' }
```

**Comment by redhog** [comment]
Fixed the unit test bug

**Comment by enriquetuya** [comment]
Tested on client 0.15.1
